# -*- coding: utf-8 -*-
"""svm_model end term

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12_ghpsSxFWSb9AXWYA0o8WEff_ijMSRY
"""

import numpy as np

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/content/drive/My Drive/svm model /final merge 2.csv")
# df.tail()
df = np.array(df)
np.unique(df)





df2 =pd.read_csv("/content/drive/My Drive/svm model /Copy of final merge end viva.csv")
# df2.tail()
df2 = np.array(df2)
np.unique(df2)

X_tr,X_ts,D_tr,D_ts=train_test_split(df2,df,test_size=0.40)

# model=SVC()
model=SVC(kernel='poly', degree=2, C=6).fit(X_tr, D_tr)

# model.fit(X_tr,D_tr)

predict_Cancer=model.predict(X_ts)
print(accuracy_score(D_ts,predict_Cancer))